### ISSUE TITLE
Old BÍN data?

### ISSUE THREAD

**Issue by atlijas** [mideind/BinPackage#16]
>>> from islenska.bincompress import BinCompressed
    >>> bin_com = BinCompressed()
    >>> bin_com.lookup('Möðrudalsöræfum')
    []
    >>> bin_com.lookup('Möðrudalsöræfi')
    [('Möðrudalsöræfi', 489454, 'hk', 'örn', 'Möðrudalsöræfi', 'ÞFET'), ('Möðrudalsöræfi', 489454, 'hk', 'örn', 'Möðrudalsöræfi', 'ÞGFET'), ('Möðrudalsöræfi', 489454, 'hk', 'örn', 'Möðrudalsöræfi', 'NFET')]

_Möðrudalsöræfi_ should be plural but bin_com.lookup returns the singular form (which I don't think really exists). I have an old copy of [Sigrúnarsnið](https://bin.arnastofnun.is/gogn/SH-snid) (downloaded in June 2022) where this also seems to be the case. In the latest version of Sigrúnarsnið, this has been rectified.

**Comment by sveinbjornt** [comment]
The latest version of BinPackage was released on Jan 12th, 2023, so this must have been fixed in BÍN after that date. Will probably get automatically rectified next time we make a new release. In the meantime, you can always build BinPackage yourself to use the absolutely latest corpus.

**Comment by atlijas** [comment]
Thank you.
